version: "3"
services:
    cse_method_lab:
        build: ./method_lab
        container_name: cse_method_lab
        ports:
          - "7901:80"
        working_dir: /var/www/html

    cse_xss_lab:
        build: ./xss_lab
        container_name: cse_xss_lab
        ports:
          - "7902:80"
        working_dir: /var/www/html

    cse_lfi_lab:
        build: ./lfi_lab
        container_name: cse_lfi_lab
        ports:
          - "7903:80"
        working_dir: /var/www/html

    cse_leak_lab:
        build: ./leak_lab
        volumes:
          - ./dotgit_for_leak_lab_1:/var/www/html/.git
        container_name: cse_leak_lab
        ports:
          - "7904:80"
        working_dir: /var/www/html

    cse_leak_lab1:
        build: ./leak_lab1
        volumes:
          - ./dotgit_for_leak_lab_2:/var/www/html/.git
        container_name: cse_leak_lab1
        ports:
          - "7905:80"
        working_dir: /var/www/html

    cse_ssrf_lab:
        build: ./ssrf_lab
        container_name: cse_ssrf_lab
        ports:
          - "7906:80"
        working_dir: /var/www/html

    cse_ssti_lab:
        build: ./ssti_lab
        container_name: cse_ssti_lab
        ports:
          - "7907:80"
        working_dir: /app

    cse_cmdi_lab:
        build: ./cmdi_lab
        container_name: cse_cmdi_lab
        ports:
          - "7908:80"
        working_dir: /var/www/html

    cse_php_lab:
        build: ./php_lab
        container_name: cse_php_lab
        ports:
          - "7909:80"
        working_dir: /var/www/html

    skill54_web_lab1:
        image: php:8.2.15-apache
        container_name: skill54_web_lab1
        volumes:
          - ./skill54_lab/web_1:/var/www/html
        ports:
          - "7910:80"
        working_dir: /var/www/html
    
    skill54_web_lab2:
        image: php:8.2.15-apache
        container_name: skill54_web_lab2
        volumes:
          - ./skill54_lab/web_2:/var/www/html
        ports:
          - "7911:80"
        working_dir: /var/www/html

    skill54_web_lab3:
        image: php:8.2.15-apache
        container_name: skill54_web_lab3
        volumes:
          - ./skill54_lab/web_3:/var/www/html
        ports:
          - "7912:80"
        working_dir: /var/www/html
